/* wave_data.h -- GENERATED by tools/waveasm.py from wave/levels.wave; DO NOT EDIT.
 * The wave/path-VM bytecode region (DGROUP 0xA0..0xCB2) and
 * the 6-entry script directory (DGROUP 0x94), rebuilt from
 * the DSL source. Byte-identity vs the loaded blob is checked
 * at boot (wave_data_check, game/game_main.c). */

#ifndef WAVE_DATA_H
#define WAVE_DATA_H

#define WAVE_BYTECODE_BASE 0xA0   /* DGROUP offset of the region */
#define WAVE_BYTECODE_LEN  0xC12
#define WAVE_DIR_BASE      0x94
#define WAVE_DIR_N         6

extern const unsigned char  wave_bytecode[WAVE_BYTECODE_LEN];
extern const unsigned short wave_script_dir[WAVE_DIR_N];

#endif
